language: node_js
node_js:
- node
build: npm build-prod
test: ''
env:
  global:
  - secure: O+t99C/18cxuJdEL8NbrdfExxjGYJ/bIazM25f4UOb26ixgV72pIeehV6Hyrl5V3pf1vuJyDlTKCNxeJpcxPf5te6/QNeazzadt9QNdDORI7VbHexE99fG6Fmb+iwmjgH3Dbw0T4/2gOM9dIsDaXLa+wdW50IcYXZh8dRIjy0nCibYjpNWHBJ/xqczpM73gpaY8lLPw2BQBP35VonuM4o7WotlySYeRQI+kLMRqVxtC2HFCw3rTwxpkSls5SH6qSOnQCz3BTyNd/bd/Yhr+TDUlgSMPwXWB13LVJR5VjN9nrv5NG7ut62PKnTK3OS4gD732zUeJLSquaFE392pC/ibOr8xgdiJlIvnxJ+IYQOi/NdMxejMJU0edGFZJes0/7F0Rw4UETJa3TThscj11o/SM5fEM1XL1Mj/kL3Y/8hZgEIB3j4ZtIrOzw1l58rFeO8WkkMZHL22zmDMMw99QrpI5oSMB1GcJkK1+0HvMkLSnMUq5ZNJNbgW1cw7sSm5aYDJRu2ruZTx0qHJqz+CgyIM0JnAI3+lOzB03l3pVyR1862hqJHctou5Yc7w5ft/iYnbgis2XIPb9hMQbojTtCZUnxAHqPRtK5NELpMUVnO54xsq/boTmRIY0ODbq4MmkdK01gZKHZBWvOk7RxZUMXM170eObUt5fYgFptXHeZYY8=
  - secure: HNg4GRljfcTHtndbQE2kTYJu8j2QuFnYqfOCEIqa14m2kS+M9PC2lWbxYAvoIhm2e4S0X139f7TPYKPiNiyRKUWq0qkaehuh3O0NMXnYtk5YC/DqTSowXvOv1/wx/pV16Mpox45TjxOmrbeOwd9kojee3gqS+h3PxzNJHwZsnBLCh3L0uuT7zzgO5Ug+tn1WeUahYAgeutV21Y643j6q6MS7KPB/9LqkTQGplg/+rIbZm//2QtMoqxmK3AIhY1PiSpEKlrRitR+A9uIsBP67sHeTm43GMhBIA/XPeF7yEURTEsqF8RZb6nOOjcVqzpft2CNyzSTcOoS7iiXhooNx0IOAUFZQIDSV+XA2LsGD7C3cUZP4C7JbGuLSXxZsOQ9swvZhhbIyk8EyFneTcgLNisL1uRin7MsKnjyjSedx7Uoac0wt8VaE407lXc3eiuNOaIC5ht37LqXuevXawi4IPwrh1Ml93Y+vIw2y7pJbcb0r/1akcU4EjeAapt64KgNi3fXKTGgt+VzpPmGjANSPYreHaAWgSBAUtnSZFfwcEmm9cKg0gzEh3z/Y1DP3QvhJOcoTwGy3/zD0ZX0mXA6hWSnKCh3Dyxfryp6GQLZPirBeK9zZbfbYp9xQBsY3y7oKl0wLll+0AbKfei0CUz8ZLO4i/OphWDdYDmKSlu244Pk=
before_install:
- openssl aes-256-cbc -K $encrypted_e64c3ee27018_key -iv $encrypted_e64c3ee27018_iv
  -in deploy_rsa.enc -out deploy_rsa -d
deploy:
- provider: script
  script: "sshpass -p $PASSPHRASE scp -i deploy_rsa -r dist/* magic-deploy@magic.zyuiop.net:$DEPLOY_PATH"
  on:
    branch: master
